### PR TITLE
Refactor to MirageJS

### PR DESCRIPTION
**Pull request by minkimcello**
## Motivation
Screen Shot 2020-07-14 at 4 57 15 PM
This is part of an on-going initiative to completely migrate all of `folio-org` projects from `@bigtest/mirage` to `miragejs`.

[`@bigtest/mirage`](https://github.com/bigtestjs/mirage/) was originally a prototype to make `mirage` available to any framework, but it has since been archived in favor of [`miragejs`](https://miragejs.com/). The documentation for `miragejs` is not only prodigious for its extensive API docs but also for its tutorials and guides. Furthermore, it receives regular bug-fixes and maintenance releases in thanks to its extremely large and active community.

Previous PR: [@folio-org/ui-marccat #462](https://github.com/folio-org/ui-marccat/pull/462)
_Linking the previous pull request so that subsequent ones can be found tagged below._

<details>
<summary>Overview of progress at the time of the creation of this PR (in chronological order):</summary>
<br>
✅ <code>ui-checkin</code>
<br>
✅ <code>ui-checkout</code>
<br>
☑️ <code>ui-circulation</code>
<br>
☑️ <code>ui-calendar</code>
<br>
✅ <code>ui-agreements</code>
<br>
☑️ <code>ui-app-template</code>
<br>
☑️ <code>ui-inventory</code>
<br>
☑️ <code>ui-data-export</code>
<br>
✅ <code>ui-finc-config</code>
<br>
☑️ <code>ui-licenses</code>
<br>
☑️ <code>ui-erm-comparisons</code>
<br>
☑️ <code>ui-myprofile</code>
<br>
☑️ <code>ui-local-kb-admin</code>
<br>
☑️ <code>ui-marccat</code>
<br>
☑️ <code>ui-finc-select</code>
</details>

## Approach
- [x] Cloned, installed, and then ran tests to double check that the tests are passing before refactoring.
- [x] Removed `@bigtest/mirage` and added `inflected` and `miragejs`.
- [x] `<ConfirmationModal />` is imported in two different locations and only one of them requires `onDelete()` resulting in the other component returning an error for the missing function so I provided it with a default empty function to mitigate the error.
- [x] :warning: Debug test suites:
  - This popup appears both before and after the miragejs refactor:
  Screen Shot 2020-07-27 at 2 32 03 PM
      - @rchr Could the `collectionsIds` error be from [this](https://github.com/folio-org/ui-finc-select/pull/134) PR?
  - `json.fincSelectFilters` is passed in [here](https://github.com/folio-org/ui-finc-select/blob/master/test/bigtest/network/serializers/finc-select-filter.js#L16) and returned as `undefined` again in both before and after the refactor. Adding an `or` conditional and passing in an empty object will allow the tests to pass.
  - :warning: :warning: Created an JIRA issue [here](https://issues.folio.org/browse/UIFC-199) :warning: :warning:
- [x] ESlint & ran tests after the refactor to confirm they all pass.
  - ⚠️ See bullet point above. Tests are passing but not satisfyingly but it's out of scope of what this pull request is about.

### CODE REVIEW

**Comment by minkimcello** [comment]
@taras @zburke The tests are passing despite some concerning errors that are popping up in debug mode. They don't seem to be related to the actual mirage refactor because you get the same same payload and errors when you run tests on `master`. I don't know how deep I should be digging into this.

**Comment by zburke** [comment]
>  I don't know how deep I should be digging into this.

My gut reaction is "not deep at all." I think it's best to keep the scope of this PR narrowly focused on mirage. If you are willing to write up a ticket for test errors in UIFC, that would be great. Alternatively, we'll tag @elsenhans and @rchr so they know about the test errors in case they already have WIP.

**Comment by elsenhans** [comment]
@minkimcello sorry for late response. I will take care about the errors in UIFC.

**Comment by minkimcello** [comment]
@elsenhans Are you going to post the issue on JIRA or should I?

**Comment by elsenhans** [comment]
For the Translation errors is already one ticket: https://issues.folio.org/browse/UIFC-198

**Comment by minkimcello** [comment]
@elsenhans What about the bugs listed in this PR body?

**Comment by elsenhans** [comment]
@minkimcello can you open a jira ticket for those bugs please?

**Comment by minkimcello** [comment]
@elsenhans Done. Created issue [here](https://issues.folio.org/browse/UIFC-199). I don't have write access to this repository so could you tag reviewers for me?

**Comment by elsenhans** [comment]
Thanks!

**Comment by rchr** [comment]
@minkimcello I changed some factories and models to use singular names [(PR-147)](https://github.com/folio-org/ui-finc-select/pull/147). When merging this into your branch (`mk/miragejs`) locally, the tests run successfully.
Can you merge it to your branch, so that the PR checks will pass as well?

**Comment by minkimcello** [comment]
@rchr Thank you 🙏

**Pull request merged**
